{% set name = "libtins" %}
{% set version = "4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mfontanini/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6ff5fe1ada10daef8538743dccb9c9b3e19d05d028ffdc24838e62ff3fc55841

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libtins', max_pin='x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

  host:
    - libpcap
    - openssl  # [osx]

test:
  commands:
    - test -f $PREFIX/include/tins/tins.h  # [not win]
    - test -f $PREFIX/lib/libtins${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\Library\bin\tins.dll exit 1  # [win]
    - if not exist %PREFIX%\Library\include\tins\tins.h exit 1  # [win]

about:
  home: https://github.com/mfontanini/libtins
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: libtins is a high-level, multiplatform C++ network packet sniffing and crafting library
  description: |
    Its main purpose is to provide the C++ developer an easy,
    efficient, platform and endianess-independent way to create tools
    which need to send, receive and manipulate specially crafted
    packets.

extra:
  recipe-maintainers:
    - costrouc
    - tylerpotts
